---
abstract: 'Test your Catalyst application with Selenium'
author:
  - 'Ash Berlin C<< <ash@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  IPC::Cmd: 0.42
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Selenium-Catalyst
no_index:
  directory:
    - inc
    - t
requires:
  Alien::SeleniumRC: 0
  Catalyst::Runtime: 5.9
  Catalyst::Utils: 0
  Test::More: 0
  Test::WWW::Selenium: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://git.shadowcat.co.uk/catagits/Test-WWW-Selenium-Catalyst.git
version: 0.07
