---
abstract: 'Test your Catalyst application with Selenium'
author:
  - 'Ash Berlin C<< <ash@cpan.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.790'
license: Perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-WWW-Selenium-Catalyst
no_index:
  directory:
    - inc
    - t
requires:
  Alien::SeleniumRC: 0
  Catalyst::Runtime: 5.7001
  Catalyst::Utils: 0
  Test::More: 0
  Test::WWW::Selenium: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
